name: Check PHP code style

on: [push]

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Check style
                uses: docker://oskarstark/php-cs-fixer-ga
                with:
                    args: --config=.php-cs-fixer.php --dry-run --diff
