name: tests

on:
  push:
    branches:
      - master
      - 1.x
      - 2.x
    paths-ignore:
      - LICENSE.md
      - readme.md
  pull_request:
    paths-ignore:
      - LICENSE.md
      - readme.md

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3]

    name: PHP ${{ matrix.php }} on Linux

    env:
      PHPUNIT_PACKAGE: ${{ matrix.php == '8.1' && 'phpunit/phpunit:^10.1' || 'phpunit/phpunit:^11.0' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip
        tools: composer:v2
        coverage: none

    - name: Install dependencies
      run: |
        composer require "$PHPUNIT_PACKAGE" --dev --no-update
        composer update --prefer-dist --no-interaction --no-progress --ansi

    - name: Install Geckodriver
      run: vendor/bin/phpunit tests/DownloadBinaries.php

    - name: Execute tests
      run: vendor/bin/phpunit
  mac_tests:
    runs-on: macos-latest

    strategy:
      matrix:
        php: [8.3]

    name: PHP ${{ matrix.php }} on MacOS

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip
        tools: composer:v2
        coverage: none

    - name: Install dependencies
      run: |
        composer require "phpunit/phpunit:^11.0" --dev --no-update
        composer update --prefer-dist --no-interaction --no-progress --ansi

    - name: Install Geckodriver
      run: vendor/bin/phpunit tests/DownloadBinaries.php

    - name: Execute tests
      run: vendor/bin/phpunit
  windows_tests:
    runs-on: windows-latest

    strategy:
      matrix:
        php: [8.3]

    name: PHP ${{ matrix.php }} on MS Windows

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, fileinfo, libxml, mbstring, zip
        tools: composer:v2
        coverage: none

    - name: Install dependencies
      run: |
        composer require "phpunit/phpunit:^10.1" --dev --no-update
        composer update --prefer-dist --no-interaction --no-progress --ansi

    - name: Install Geckodriver
      run: vendor/bin/phpunit tests/DownloadBinaries.php

    - name: Execute tests
      run: vendor/bin/phpunit
